name: Go

on:
  push:
    branches: [ master ]

env:
  imageRepository: 'go-app'
  resourceGroupName: 'ashmilTest'
  containerRegistryName: 'MyRegistryAshmil'
  containerRegistry: 'myregistryashmil.azurecr.io'
  dockerfilePath: '.'
  tag: '${{ github.run_id  }}'


jobs:

  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Build and push an image to container registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        path: ${{ env.dockerfilePath  }}
        dockerfile: '${{ env.dockerfilePath }}/Dockerfile'
        registry: ${{ env.containerRegistry }}
        repository: ${{ env.imageRepository }}
        tags: ${{ env.tag }},latest
